disabled_rules:
  - dynamic_inline
  - private_unit_test
  - type_body_length
  - valid_ibinspectable
  - function_default_parameter_at_end
  - nesting
  - switch_case_alignment
opt_in_rules:
  - closure_spacing
  - convenience_type
  - discouraged_object_literal
  - empty_string
  - fallthrough
  - fatal_error_message
  - first_where
  - multiline_arguments
  - multiline_parameters
  - overridden_super_call
  - override_in_extension
  - required_enum_case
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - array_init
  - explicit_init
  - function_default_parameter_at_end
  - redundant_nil_coalescing
  - closure_body_length
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - enum_case_associated_values_count
  - file_name_no_space
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - no_extension_access_modifier
  - nslocalizedstring_key
  - operator_usage_whitespace
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unused_declaration
  - unused_import
  - vertical_whitespace_closing_braces
  - closure_end_indentation
  - multiline_function_chains
  - weak_delegate

closing_brace:
  severity: error
closure_body_length:
  - 30 #warning
  - 40 #error
closure_end_indentation:
  severity: error
colon:
  severity: error
  flexible_right_spacing: false
  apply_to_dictionaries: true
comma:
  severity: error
conditional_returns_on_newline:
  severity: error
  if_only: true
control_statement:
  severity: error
cyclomatic_complexity:
  - 7 #warning
  - 8 #error
empty_count:
  severity: error
empty_parameters:
  severity: error
explicit_init:
  severity: error
file_length:
  warning: 300
  error: 400
force_cast:
  severity: error
force_try:
  severity: error
function_body_length:
  - 60 #warning
  - 80 #error
function_parameter_count:
  - 5 #warning
  - 6 #error
implicit_getter:
  severity: error
large_tuple:
  - 3 #warning
  - 5 #error
leading_whitespace:
  severity: error
legacy_cggeometry_functions:
  severity: error
legacy_constant:
  severity: error
legacy_constructor:
  severity: error
legacy_nsgeometry_functions:
  severity: error
line_length:
  ignores_comments: true
  warning: 110
  error: 120
mark:
  severity: error
opening_brace:
  severity: error
operator_usage_whitespace:
  severity: error
operator_whitespace:
  severity: error
overridden_super_call:
  severity: error
redundant_nil_coalescing:
  severity: error
redundant_optional_initialization:
  severity: error
redundant_string_enum_value:
  severity: error
redundant_void_return:
  severity: error
return_arrow_whitespace:
  severity: error
syntactic_sugar:
  severity: error
todo:
  severity: warning
trailing_comma:
  severity: error
trailing_newline:
  severity: error
trailing_semicolon:
  severity: error
trailing_whitespace:
  severity: warning
type_name:
  max_length: 45
  severity: error
  excluded:
    - T
    - U
unused_closure_parameter:
  severity: error
identifier_name:
  min_length: 2
  severity: error
vertical_parameter_alignment:
  severity: error
vertical_whitespace:
  severity: error
void_return:
  severity: error
weak_delegate:
  severity: error
first_where:
  severity: error
private_action:
  severity: error
private_outlet:
  severity: error
closure_spacing:
  severity: error
multiline_function_chains:
  severity: error
array_init:
  severity: error
statement_position:
  severity: error
unused_enumerated:
  severity: error
vertical_parameter_alignment_on_call:
  severity: error
empty_string:
  severity: error
unneeded_break_in_switch:
  severity: error
fatal_error_message:
  severity: error
empty_parentheses_with_trailing_closure:
  severity: error
contains_over_first_not_nil:
  severity: error
