name: GitHubUserFinderKMM-Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - "*.png"
      - docs
      - ios

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Verify and generate coverage report
        run: ./gradlew koverMergedXmlReport --stacktrace

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: shared-test-report
          path: ${{ github.workspace }}/build/reports/kover/merged/xml/report.xml
          retention-days: 5

      - name: Build
        run: ./gradlew check --stacktrace

  test-report:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Download report
        uses: actions/download-artifact@v3
        with:
          name: shared-test-report

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1.6
        with:
          path: ${{ github.workspace }}/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true