name: GitHubUserFinderKMM-Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - "*.png"
      - docs
      - ios

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11

      - name: Build
        run: ./gradlew build



