name: GitHubUserFinderKMM-Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - "*.png"
      - docs
      - ios

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11

      - name: Verify and generate coverage report
        run: ./gradlew koverMergedVerify koverMergedReport --stacktrace

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1.1
        with:
          path: ${{ github.workspace }}/build/reports/kover/merged/xml/report.xml
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true

      - name: Build
        run: ./gradlew check --stacktrace
