name: GitHubUserFinderKMM-iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - "*.png"
      - docs
      - androidApp

defaults:
  run:
    working-directory: ./iosApp

jobs:
  SwiftLint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.2
      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1

  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.11.0
        with:
          distribution: corretto
          java-version: 18

      - name: Grant execute permission for gradlew
        run: chmod +x ../gradlew

      - name: Select Xcode version
        run: |
          sudo xcode-select -s /Applications/Xcode_14.3.app

      - name: Build
        run: |
          xcodebuild build-for-testing \
            -scheme iosApp \
            -project iosApp.xcodeproj \
            -destination "platform=iOS Simulator,name=iPhone 11"
