name: GitHubUserFinderKMM

on:
  workflow_dispatch:
  push:
    branches:
      - development
  pull_request:
    paths-ignore:
      - "**.md"
      - "*.png"
      - docs

defaults:
  run:
    working-directory: ./iosApp

jobs:
  SwiftLint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.2
      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1

  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.2

      - uses: actions/setup-java@v3.11.0
        with:
          distribution: corretto
          java-version: 18

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Verify and generate coverage report
        run: ./gradlew koverMergedXmlReport --stacktrace

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: shared-test-report
          path: ${{ github.workspace }}/build/reports/kover/merged/xml/report.xml
          retention-days: 5

      - name: Build
        run: ./gradlew check --stacktrace

  test-report:
    needs: build-android
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Download report
        uses: actions/download-artifact@v3
        with:
          name: shared-test-report

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1.6
        with:
          path: ${{ github.workspace }}/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true

  build-ios:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.11.0
        with:
          distribution: corretto
          java-version: 18

      - name: Grant execute permission for gradlew
        run: chmod +x ../gradlew

      - name: Select Xcode version
        run: |
          sudo xcode-select -s /Applications/Xcode_14.3.app

      - name: Build
        run: |
          xcodebuild build-for-testing \
            -scheme iosApp \
            -project iosApp.xcodeproj \
            -destination "platform=iOS Simulator,name=iPhone 11"

  build:
    needs: [build-android, build-ios]